### ISSUE TITLE
load-our-ssh-keys() function doesn't work on Arch Linux

### ISSUE THREAD

**Issue by dglynn** [unixorn/zsh-quickstart-kit#141] opened 2021-11-01 12:06 UTC
I am not sure if this is Arch specific but my ssh key is never loaded during the start-up of a new shell/terminal.

I see output like this:

```
-- console output produced during zsh initialization follows --

load-our-ssh-keys:6: no such file or directory: .ssh/ssh-agent
cat: .ssh/ssh-agent: No such file or directory
Could not open a connection to your authentication agent.

Current SSH Keys:
Could not open a connection to your authentication agent.
```
I have tried debugging and because the kit redirects the [ssh-add cmd to  /dev/null](https://github.com/unixorn/zsh-quickstart-kit/blob/master/zsh/.zshrc#L133) I never see the actual error message: 

```
-- console output produced during zsh initialization follows --

Agent pid 40928
ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory```
```
If I add the ssh-add command to my config in the `~/.zshrc.d/` folder it gives the same askpass error as above. From reading up on this on a few SO pages its to do with the env var [SSH_ASKPASS](https://man.archlinux.org/man/ssh-add.1.en#ENVIRONMENT)

I have installed this package but it still fails: `community/openssh-askpass 2.1.0-3 [0B 2.61MiB] [Installed]`

I found this [link on StackExchange](https://unix.stackexchange.com/questions/571741/how-to-pass-a-passphrase-to-ssh-add-without-triggering-a-prompt), it may be helpful.

**Comment by unixorn** [comment] 2021-11-04 14:05
Good catch. I need to fix those whether or not they're the cause of the Arch issue

**Comment by unixorn** [comment] 2021-11-04 18:28
@dglynn I've patched those references, lmk if it fixes the problem for you so I can close this issue, thanks!

**Comment by dglynn** [comment] 2021-11-05 11:15
Yeah, no help for me sorry.

**Comment by unixorn** [comment] 2021-11-05 16:46
NP, they needed fixing anyway. I'm pretty busy this weekend but I'll try to spin up an Arch VM to debug with. What version of Arch are you running?

**Comment by dglynn** [comment] 2021-11-06 08:33
Arch is a rolling distro, I am running kernel version `5.14.14-arch1-1`

**Comment by deadc** [comment] 2021-11-17 23:20
@dglynn, I know this may be a silly question, but the `~/.ssh` folder exists in your home directory right?

I'm running Arch Linux with no problems with ssh-agent, so this might be something related to your environment and, looking at the function, it's not checking that the `~/.ssh` folder actually exists and can be the root of your problem.

**Comment by unixorn** [comment] 2021-11-17 23:38
Good catch @deadc, I'll add an existence check

**Comment by deadc** [comment] 2021-11-17 23:44
oh sorry. I've opened a PR about this
- https://github.com/unixorn/zsh-quickstart-kit/pull/151

**Comment by unixorn** [comment] 2021-11-18 00:06
NP, I saw yours before I wrote anything :-)

**Comment by dglynn** [comment] 2021-11-18 07:37
Ok I will grab the latest master and test, good find @deadc. I do have a `~/.ssh` :wink:  folder for sure, otherwise my `ssh-add` cmd wouldn't work in the first place as I said above. :point_up:

**Comment by dglynn** [comment] 2021-11-18 07:47
This doesn't seem to help me either, my agent is running, it can create the ssh-agent file but still no identity was added. :cry:

```
1 Running agent exists before the if check for ~/.ssh on 107
Agent pid 17730

Current SSH Keys:
The agent has no identities.

**Comment by unixorn** [comment] 2021-11-18 14:59
Is `ssh-askpass` in your `$PATH`? And if so, where is it? That error message makes me think something's missing from your install.

**Comment by dglynn** [comment] 2021-11-19 06:41
The ssh-askpass I installed is this one from the Arch repos: `community/openssh-askpass`

Which has a binary name of: `/usr/bin/qt4-ssh-askpass` to make things more ocmplicated.

And now this morning when starting up a terminal on my machine it's starting working again. :confused:

**Closed** 2021-11-19 12:02 UTC

**Comment by unixorn** [comment] 2021-11-19 14:07
Thanks, sorry it took so long to sort it out.

**Comment by dglynn** [comment] 2021-11-19 15:42
Yeah no worries, thanks again. :+1:
