### ISSUE TITLE
[BUG] command not found: python

### ISSUE THREAD

**Issue by neiromaster** [unixorn/zsh-quickstart-kit#216] opened 2022-08-30 15:52 UTC
# Describe the bug

After each plugin update, an error occurs:
```
Creating a zgenom save
(anon):16: command not found: python
(anon):16: command not found: python
-- zgenom: Creating `/Users/user/.zgenom/init.zsh` ...
-- zgenom: Initializing completions ...
-- zgenom: Compiling files ...
```
Error appears on macOS and Ubuntu Linux

## To Reproduce

1. Run `zqs update`
2. Close the terminal
3. Open the terminal

## Expected behavior

I wish there was no error. And I don't even know if everything works correctly after that

## Desktop (please complete the following information):

- OS/distro: macOS, Ubuntu (possible on all systems that have `python3` and `python2` instead of one `python`)

**Comment by jfmcdowell** [comment] 2022-09-06 23:17
Similar to #180

**Comment by unixorn** [comment] 2022-09-14 21:23
Yeah, closing this as a dupe of #180 which I really need to make a good fix for

**Closed by unixorn** 2022-09-14 21:23 UTC
Labels: bug
